ci: fix gcc 11.4 issue
../src/handmadehero_audio.c: In function ‘OutputPlayingAudios’:
../src/handmadehero_audio.c:59:9: error: variable-sized object may not be initialized
   59 |         b32 volumeEnded[outputChannelCount] = {};
      |         ^~~

You can test below code at https://godbolt.org/ with `x86-64 gcc 11.4`
compiler in `C`. Turning into enum lets us see variable in debugger
instead of #define.

```
typedef __UINT32_TYPE__ u32;
typedef u32 b32;

void test(void) {
  u32 outputChannelCount = 3;
  b32 volumeEnded[outputChannelCount] = {};
}
```