meson: fix linking game code with gcc compiler
__builtin_round() on gcc needs to be linked with math library
$ rm -rf build; CC=gcc meson setup build; ninja -C build/
ld: libhandmadehero.so.p/src_handmadehero.c.o: in function `roundf32tou32':
../src/handmadehero.c:23:(.text+0x115): undefined reference to `round'
collect2: error: ld returned 1 exit status

https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html
...
Many of these functions are only optimized in certain cases;
if they are not optimized in a particular case, a call to the library function is emitted.
...