meson: fix gcc compile error when variable set but not used on debug builds
do not care for unused variables on debug builds
../src/handmadehero.c: In function ‘GameUpdateAndRender’:
../src/handmadehero.c:704:15: error: variable ‘ddPlayer’ set but not used [-Werror=unused-but-set-variable]
  704 |     struct v2 ddPlayer = {};
      |               ^~~~~~~~